export const listTypeSupport = [
  {
    name: 'Nation',
    data: [
      'Cayman Islands',
      'Switzerland',
      'Maldives',
      'Bahamas',
      'Tokelau',
      'Yemen',
      'Trinidad and Tobago',
      'Macao',
      'Trinidad and Tobago',
      'Faroe Islands',
      'Croatia',
      'Saint Helena',
      'Bulgaria',
      'Albania',
      'Peru',
      'United Arab Emirates',
      'British Indian Ocean Territory (Chagos Archipelago)',
      'Panama',
      'Morocco',
      'Faroe Islands',
      'Macedonia',
      'Chile',
      'South Georgia and the South Sandwich Islands',
      'Cook Islands',
      'Azerbaijan',
      'Brazil',
      'Malta',
      'Saint Barthelemy',
      'Mali',
      'Cook Islands',
      'Thailand',
      'Rwanda',
      'Macedonia',
      'Iran',
      'Antigua and Barbuda',
      'Costa Rica',
      'Russian Federation',
      'Egypt',
      'Sweden',
      'Seychelles',
      'Dominican Republic',
      'Mauritius',
      'United States of America',
      'Turkmenistan',
      'Montserrat',
      'Comoros',
      'Czech Republic',
      'Switzerland',
      'Micronesia',
      'Brazil'
    ],
    type: 'address'
  },
  {
    name: 'City',
    data: [
      'Bernhardtown',
      'Alessandraview',
      'New Dayana',
      'East Eulahcester',
      'East Josephine',
      'Lake Darleneborough',
      'Myrtishaven',
      'East Gussie',
      'Port Maximus',
      'South Raymond',
      'South Carliborough',
      'Lake Kris',
      'New Andreanne',
      'Fort Helgaburgh',
      'West Vicentefurt',
      'East Bettestad',
      'Conroe',
      'Susannaport',
      'Broderickfurt',
      'South Rebekahmouth',
      'Fort Edgardo',
      'East Alysa',
      'Laceystead',
      'Pacochaboro',
      'Conroe',
      'Anaheim',
      'Bettiehaven',
      'Fort Marciaburgh',
      'Kannapolis',
      'Edinburg',
      'Fort Kristophertown',
      'Collierville',
      'Idellaland',
      'Opheliaburgh',
      'South Mckenzieport',
      'Lake Bartstead',
      'Frederikchester',
      'New Isobel',
      'Guiseppeport',
      'Russelfield',
      'Catonsville',
      'Donnellystad',
      'East Reed',
      'Port Jared',
      'Larryland',
      'West Blaisestad',
      'Port Vickie',
      'Bergnaumcester',
      'Pine Hills',
      'Zboncakworth'
    ],
    type: 'address'
  },
  {
    name: 'Street',
    data: [
      '3874 Marks Inlet',
      '11935 Claire Hill',
      '34931 Rosemarie Trafficway',
      '0725 Susan Spurs',
      '20483 Trantow Walk',
      '425 Quigley Court',
      '10567 Verdie Curve',
      '6251 Considine Greens',
      '357 Jasmin Mountain',
      '095 Larkin Valleys',
      '26525 Hermann Villages',
      '1127 Shad Crossroad',
      '0720 Mallory Fork',
      '94942 Leonel Unions',
      '35764 Hermann Prairie',
      '92530 Vada Cove',
      '943 Lavonne Estates',
      '523 Heathcote Branch',
      '22694 Lynch Way',
      '60706 Margarete Row',
      '80758 Alverta Gardens',
      '77644 Wilderman Trafficway',
      '870 Ryder Trafficway',
      '161 Amya Springs',
      '6602 Russel Villages',
      '17491 Little Landing',
      '7009 Verla Cliff',
      '7675 Saul Club',
      '7520 Beatty Tunnel',
      '7377 Terrill Trail',
      '340 Altenwerth Mall',
      '4382 Presley Terrace',
      '4120 Reichel Corner',
      '4348 Hartmann Mount',
      '205 McKenzie Gateway',
      '303 Koepp Place',
      '2202 Lisette Haven',
      '814 VonRueden Forks',
      '06726 Pollich Landing',
      '327 Leannon Fords',
      '5976 Tess Ville',
      '064 Prosacco Via',
      '1929 Franco Brook',
      '12706 Garnet Keys',
      '672 Cummerata Parkways',
      '32930 Shayna Causeway',
      '512 Alberta Mews',
      '40434 Yessenia Stravenue',
      '83539 Betsy Mountain',
      '01890 Powlowski Canyon'
    ],
    type: 'address'
  },
  {
    name: 'FastFood',
    data: [
      'Burger',
      'Pizza',
      'Fries',
      'Hot Dog',
      'Chicken Nuggets',
      'Taco',
      'Burrito',
      'Sandwich',
      'Chicken Wings',
      'Submarine Sandwich',
      'Fried Chicken',
      'French Fries',
      'Onion Rings',
      'Milkshake',
      'Soft Drink',
      'Cheeseburger',
      'Fish and Chips',
      'Sushi',
      'Quesadilla',
      'Wrap',
      'Donut',
      'Ice Cream',
      'Pancakes',
      'Waffles',
      'Tiramisu',
      'Chicken Sandwich',
      'Grilled Cheese Sandwich',
      'Muffin',
      'Hash Browns',
      'Egg Rolls',
      'Spring Rolls',
      'Tater Tots',
      'Chili Dog',
      'Nachos',
      'Pretzel',
      'Popcorn Chicken',
      'Poutine',
      'Corn Dog',
      'Fried Rice',
      'Egg McMuffin',
      'Baconator',
      'Bacon Cheeseburger',
      'McChicken',
      'Filet-O-Fish',
      'Big Mac',
      'Whopper',
      'McDouble',
      'Quarter Pounder',
      'Chick-fil-A Sandwich',
      'Chicken Tenders',
      'McNuggets',
      "Arby's Roast Beef Sandwich",
      'DQ Blizzard',
      'Sonic Blast',
      "Wendy's Frosty",
      'KFC Original Recipe Chicken',
      'KFC Popcorn Chicken',
      'KFC Chicken Tenders',
      'KFC Famous Bowl',
      'Taco Bell Crunchwrap Supreme',
      'Taco Bell Doritos Locos Tacos',
      'Taco Bell Quesarito',
      'Taco Bell Nachos BellGrande',
      'Subway Footlong',
      'Subway Meatball Marinara',
      'Subway Chicken Teriyaki',
      'Subway Italian B.M.T.',
      'Subway Veggie Delight',
      "Domino's Pepperoni Pizza",
      "Domino's Cheese Pizza",
      "Domino's Hawaiian Pizza",
      "Domino's Philly Cheese Steak Pizza",
      "Domino's Buffalo Chicken Pizza",
      "Domino's Breadsticks",
      "Domino's Cinna Stix",
      'Pizza Hut Pepperoni Pizza',
      'Pizza Hut Cheese Pizza',
      'Pizza Hut Meat Lovers Pizza',
      'Pizza Hut Supreme Pizza',
      'Pizza Hut Stuffed Crust Pizza',
      'Krispy Kreme Original Glazed Doughnut',
      'Krispy Kreme Chocolate Glazed Doughnut',
      'Krispy Kreme Jelly Doughnut',
      'Krispy Kreme Custard Filled Doughnut',
      'Krispy Kreme Glazed Raspberry Filled Doughnut',
      "McDonald's Apple Pie",
      "McDonald's French Fries",
      "McDonald's Chicken McNuggets",
      "McDonald's Big Mac",
      "McDonald's Egg McMuffin",
      "McDonald's Quarter Pounder",
      'Burger King Whopper',
      'Burger King Chicken Fries',
      'Burger King Onion Rings',
      'Burger King French Toast Sticks',
      'Burger King Chicken Nuggets'
    ],
    type: 'product'
  },
  {
    name: 'MainFood',
    data: [
      'Pizza',
      'Pasta',
      'Rice',
      'Noodles',
      'Bread',
      'Meat',
      'Fish',
      'Chicken',
      'Eggs',
      'Cheese',
      'Yogurt',
      'Tofu',
      'Tempeh',
      'Seitan',
      'Beans',
      'Lentils',
      'Nuts',
      'Seeds',
      'Vegetables',
      'Fruits',
      'Soup',
      'Stew',
      'Chili',
      'Curry',
      'Stir-fry',
      'Salad',
      'Sandwich',
      'Burger',
      'Taco',
      'Burrito',
      'Enchilada',
      'Tamale',
      'Pierogi',
      'Dumpling',
      'Empanada',
      'Samosa',
      'Spring roll',
      'Sushi',
      'Sashimi',
      'Ceviche',
      'Poke',
      'Tartar',
      'Carpaccio',
      'Bruschetta',
      'Crostini',
      'Tapas',
      'Mezze',
      'Dim sum',
      'Baozi',
      'Banh mi',
      'Pho',
      'Ramen',
      'Udon',
      'Soba',
      'Bibimbap',
      'Bulgogi',
      'Tteokbokki',
      'Pad thai',
      'Massaman curry',
      'Green curry',
      'Pad see ew',
      'Tom yum soup',
      'Khao soi',
      'Som tum',
      'Larb',
      'Gaeng keow wan',
      'Phanaeng curry',
      'Rendang',
      'Nasi goreng',
      'Biryani',
      'Tikka masala',
      'Rogan josh',
      'Vindaloo',
      'Korma',
      'Falafel',
      'Hummus',
      'Baba ganoush',
      'Tabbouleh',
      'Fattoush',
      'Kibbeh',
      'Mujaddara',
      'Mansaf',
      'Couscous',
      'Tagine',
      'Shawarma',
      'Baklava',
      'Güllaç',
      'Kanafeh',
      'Maamoul',
      'Baklava',
      'Halva',
      'Turkish delight',
      'Ice cream',
      'Cake',
      'Pie',
      'Cookies',
      'Brownies',
      'Doughnuts',
      'Muffins',
      'Pancakes'
    ],
    type: 'product'
  },
  {
    name: 'Drink',
    data: [
      'Water',
      'Coffee',
      'Tea',
      'Juice',
      'Soda',
      'Beer',
      'Wine',
      'Spirits',
      'Cocktails',
      'Smoothies',
      'Milkshakes',
      'Energy drinks',
      'Sports drinks',
      'Flavored water',
      'Sparkling water',
      'Kombucha',
      'Kefir',
      'Apple cider',
      'Cranberry juice',
      'Grape juice',
      'Orange juice',
      'Lemonade',
      'Limeade',
      'Iced tea',
      'Hot chocolate',
      'Eggnog',
      'Apple cider vinegar',
      'Coconut water',
      'Soy milk',
      'Almond milk',
      'Oat milk',
      'Rice milk',
      'Hemp milk',
      'Cashew milk',
      'Macadamia milk',
      'Hazelnut milk',
      'Pea milk',
      'Quinoa milk',
      'Amaranth milk',
      'Buckwheat milk',
      'Teff milk',
      'Sorghum milk',
      'Millet milk',
      'Brown rice milk',
      'Black rice milk',
      'Wild rice milk',
      'Sprouted brown rice milk',
      'Sprouted black rice milk',
      'Sprouted wild rice milk',
      'Plant-based milk',
      'Sparkling wine',
      'Champagne',
      'Prosecco',
      'Sake',
      'Mead',
      'Kvass',
      'Pulque',
      'Tepache',
      'Chicha',
      'Guarapo',
      'Cauim',
      'Balché',
      'Piña colada',
      'Daiquiri',
      'Margarita',
      'Mojito',
      'Mai tai',
      'Zombie',
      'Hurricane',
      'Painkiller',
      'Mai Tai',
      'Singapore Sling',
      'Old Fashioned',
      'Manhattan',
      'Martini',
      'Negroni',
      'Boulevardier',
      'Sazerac',
      'Vieux Carré',
      'Ramos Gin Fizz',
      'Tom Collins',
      'Gimlet',
      'Vodka tonic',
      'Gin and tonic',
      'Rum and coke',
      'Tequila sunrise',
      'Bloody Mary',
      'Mimosa',
      'Bellini',
      'Aperol Spritz',
      'Hugo',
      "Pimm's Cup",
      'Dark and stormy',
      'Moscow mule',
      'Irish coffee',
      'White Russian',
      'Black Russian',
      'Espresso martini',
      'Affogato',
      'Iced coffee'
    ],
    type: 'product'
  },
  {
    name: 'Clothes',
    data: [
      'T-shirt',
      'Jeans',
      'Hoodie',
      'Dress',
      'Shirt',
      'Skirt',
      'Sweater',
      'Pants',
      'Jacket',
      'Shorts',
      'Blouse',
      'Coat',
      'Suit',
      'Cardigan',
      'Tank Top',
      'Leggings',
      'Trousers',
      'Blazer',
      'Sweatshirt',
      'Top',
      'Jumpsuit',
      'Harem Pants',
      'Kimono',
      'Polo Shirt',
      'Dungarees',
      'Halter Top',
      'Peacoat',
      'Cargo Pants',
      'Capri Pants',
      'Bomber Jacket',
      'Maxi Dress',
      'Anorak',
      'Romper',
      'Crop Top',
      'Poncho',
      'Jersey',
      'Chinos',
      'Vest',
      'Wrap Dress',
      'Overalls',
      'Flannel Shirt',
      'Parka',
      'Sweatpants',
      'Windbreaker',
      'Tunic',
      'Sarong',
      'Pullover',
      'Sheath Dress',
      'Puffer Jacket',
      'Trench Coat',
      'Sundress',
      'Rugby Shirt',
      'Cape',
      'Pencil Skirt',
      'Henley Shirt',
      'Duster Coat',
      'Blouson',
      'Culottes',
      'Jersey Dress',
      'Parka',
      'Turtleneck',
      'Dhoti Pants',
      'Fleece Jacket',
      'Shift Dress',
      'Duster Jacket',
      'Cheongsam',
      'Salwar Kameez',
      'Sherwani',
      'Lehenga',
      'Churidar',
      'Kurta',
      'Kaftan',
      'Saree',
      'Dupatta',
      'Kurta Pajama',
      'Ghagra Choli',
      'Abaya',
      'Jodhpuri Suit',
      'Sherwani',
      'Pathani Suit',
      'Bandhgala',
      'Safari Suit',
      'Dhoti Kurta',
      'Lungi',
      'Nehru Jacket',
      'Anarkali Suit',
      'Balloon Skirt',
      'Corset',
      'Bolero Jacket',
      'Fishtail Skirt',
      'Trench Coat',
      'Biker Jacket',
      'Churidar Suit',
      'Jodhpuri Suit',
      'Palazzo Pants',
      'Shawl',
      'Sweatshorts',
      'Kimono Jacket',
      'Cami Dress',
      'Cargo Shorts',
      'Patiala Suit',
      'Lehenga Choli',
      'Crop Jacket',
      'Boiler Suit',
      'Denim Jacket',
      'Toga Dress',
      'RompHim',
      'Hooded Dress',
      'Choli',
      'Churidar Kurta',
      'Kurta Pyjama',
      'Bandeau Top',
      'Bustier',
      'Haltered Dress',
      'Bolero'
    ],
    type: 'product'
  },
  {
    name: 'Job',
    data: [
      'Associate',
      'Producer',
      'Technician',
      'Architect',
      'Director',
      'Representative',
      'Architect',
      'Coordinator',
      'Supervisor',
      'Facilitator',
      'Planner',
      'Strategist',
      'Officer',
      'Coordinator',
      'Producer',
      'Administrator',
      'Analyst',
      'Producer',
      'Representative',
      'Orchestrator',
      'Facilitator',
      'Strategist',
      'Architect',
      'Representative',
      'Liaison',
      'Analyst',
      'Designer',
      'Designer',
      'Designer',
      'Facilitator',
      'Director',
      'Analyst',
      'Analyst',
      'Administrator',
      'Assistant',
      'Consultant',
      'Representative',
      'Technician',
      'Engineer',
      'Agent',
      'Supervisor',
      'Officer',
      'Director',
      'Associate',
      'Administrator',
      'Supervisor',
      'Architect',
      'Developer',
      'Supervisor',
      'Agent',
      'Producer',
      'Administrator',
      'Director',
      'Representative',
      'Coordinator',
      'Orchestrator',
      'Director',
      'Agent',
      'Administrator',
      'Technician',
      'Producer',
      'Supervisor',
      'Consultant',
      'Representative',
      'Consultant',
      'Engineer',
      'Orchestrator',
      'Executive',
      'Representative',
      'Officer',
      'Architect',
      'Consultant',
      'Representative',
      'Designer',
      'Consultant',
      'Director',
      'Analyst',
      'Engineer',
      'Facilitator',
      'Manager',
      'Architect',
      'Associate',
      'Planner',
      'Architect',
      'Producer',
      'Liaison',
      'Liaison',
      'Executive',
      'Supervisor',
      'Consultant',
      'Architect',
      'Liaison',
      'Executive',
      'Facilitator',
      'Associate',
      'Supervisor',
      'Architect',
      'Officer',
      'Liaison',
      'Producer'
    ],
    type: 'product'
  },
  {
    name: 'CompanyShip',
    data: [
      'LogiWise',
      'SwiftLogistics',
      'CargoConnect',
      'TransPorter',
      'ShipMaster',
      'FreightWorks',
      'GlobalTransit',
      'NexusLogistics',
      'SwiftShift',
      'SpeedyFreight',
      'ApexLogistics',
      'ExpressCargo',
      'PrimeLogistics',
      'TransGlobal',
      'QuickHaul',
      'ReliantLogistics',
      'RapidTransit',
      'EagleLogistics',
      'SureShift',
      'FastTrack Logistics',
      'PrecisionCargo',
      'SecureTrans',
      'AllianceLogistics',
      'MetroMover',
      'EliteLogistics',
      'DynamicCargo',
      'SwiftDispatch',
      'OptimumLogistics',
      'EfficientTrans',
      'PowerHaul',
      'MaxMove Logistics',
      'PeakPerformance Logistics',
      'ExcelTrans',
      'GlobalLink Logistics',
      'SmoothSail Logistics',
      'RedRocket Logistics',
      'StarLogistics',
      'BlueArrow Logistics',
      'DiamondTrans',
      'AlphaLogistics',
      'OmegaFreight',
      'InfinityTrans',
      'RocketLogistics',
      'HorizonHaul',
      'SummitTrans',
      'AgileLogistics',
      'VictoryLogistics',
      'HorizonTrans',
      'ApexCargo',
      'ExcelLogistics',
      'SwiftStream Logistics',
      'SkylineTrans',
      'SilverLine Logistics',
      'ExpressLink Logistics',
      'GreenGlobe Logistics',
      'UnitedTrans',
      'CrownLogistics',
      'DiamondDispatch',
      'PlatinumLogistics',
      'GoldStar Logistics',
      'RoyalTrans',
      'CapitalCargo',
      'FirstClass Logistics',
      'EagleEye Logistics',
      'CityTrans',
      'MetroMove Logistics',
      'UrbanHaul',
      'CoastalCargo',
      'PioneerLogistics',
      'PhoenixTrans',
      'LibertyLogistics',
      'SilverSail Logistics',
      'FrontierTrans',
      'GoldenGate Logistics',
      'SwiftShift Logistics',
      'DynamicDispatch',
      'MetroMile Logistics',
      'PrecisionTrans',
      'ApexExpress',
      'SwiftLine Logistics',
      'DeltaDispatch',
      'SummitShift',
      'HorizonExpress',
      'PioneerHaul',
      'EliteExpress',
      'SwiftCargo',
      'AlphaDispatch',
      'OmegaLogistics',
      'VelocityTrans',
      'SpeedyShip Logistics',
      'ReliableTrans',
      'CitySwift Logistics',
      'SwiftReach Logistics',
      'StarTrans',
      'CapitalCarrier',
      'SpeedyHaul',
      'SecureShip Logistics',
      'EagleEye Express',
      'HorizonHaul Logistics',
      'DynamicDelivery'
    ],
    type: 'name'
  },
  {
    name: 'FullName',
    data: [
      'Amos Yost',
      'Stuart Morissette',
      'Ignacio Witting I',
      'Owen Tillman',
      'Rita Fadel',
      'Dr. Otis Becker',
      'Pedro Orn',
      'Kelvin Lesch',
      'Steve Bartell',
      'Stacy Gutmann MD',
      'Scott Frami',
      'Laverne Mills',
      'Manuel Gutkowski',
      'Peter Quigley',
      'Rick Renner',
      'Muriel Hagenes',
      'Miss Rita Ortiz',
      'Rolando Barrows',
      'Zachary Frami',
      'Leslie Gusikowski MD',
      'Bessie McKenzie II',
      'Leland Bailey',
      'Carlos Wolff',
      'Emanuel Kassulke',
      'Daryl Legros IV',
      'Rachael Monahan',
      'Dr. Marjorie Rau MD',
      'Myrtle Heaney',
      'Bradford Monahan',
      'Genevieve Abernathy',
      'Emilio Monahan Jr.',
      'Simon Legros',
      'Isabel Beahan',
      'Shirley Kertzmann',
      'Woodrow Beatty',
      'Charlotte Abshire',
      'Debbie Goyette',
      'Mabel Rath PhD',
      'Sam Abbott',
      'Andrea Predovic',
      'Orville Bednar',
      'David Rempel',
      'Dora Windler',
      'Oscar Anderson',
      'Robin Jerde III',
      'Dolores Franey V',
      'Agnes Quigley',
      'Ana Windler',
      'Delores Reichert',
      'Paula Fisher V',
      'Danny Hermann',
      'Josh Bosco',
      'Arturo Trantow',
      'Roberta Corwin',
      'Gary Dare DVM',
      'Sean Wisozk',
      'Gabriel Halvorson',
      'Kari Paucek',
      'Brooke Feeney Jr.',
      'Ms. Jeff Murazik',
      'Abraham Thompson',
      'Kathleen Armstrong',
      'Samuel Lemke',
      'Charles Wisozk Jr.',
      'Peggy Turcotte',
      'Hope Hegmann',
      'Dorothy Kiehn Jr.',
      'Lela McClure',
      'Ronnie Pollich',
      'Charles Stoltenberg',
      'Winston Olson',
      'Dr. Rosemary Bosco',
      'Herman Kunze MD',
      'Tracey Schamberger',
      'Mark Shields',
      'Kara West',
      'Isabel Goldner',
      'Ron Schaden',
      'Tonya Ferry',
      'Debbie Beer II',
      'Tony Bahringer',
      'Kent Hudson',
      'Lisa Bogan',
      'Jacquelyn Braun',
      'Vincent Botsford',
      'Becky Dach',
      'Daryl Dickinson',
      'Kerry Bogan',
      'Dr. Sidney Steuber',
      'Nicholas Stanton',
      'Colin Bins',
      'Barbara Rau',
      'Benny Labadie',
      'Casey Kling',
      'Cynthia Altenwerth',
      'Darla Lakin',
      'Preston Jast',
      'Miss Winifred Schoen',
      'Ms. Franklin Beatty',
      'Ian Gerhold DDS'
    ],
    type: 'name'
  },
  {
    name: 'Fruits',
    data: [
      'Apple',
      'Banana',
      'Orange',
      'Grape',
      'Strawberry',
      'Watermelon',
      'Pineapple',
      'Mango',
      'Kiwi',
      'Blueberry',
      'Peach',
      'Pear',
      'Cherry',
      'Plum',
      'Raspberry',
      'Blackberry',
      'Cantaloupe',
      'Honeydew',
      'Lemon',
      'Lime',
      'Coconut',
      'Grapefruit',
      'Pomegranate',
      'Apricot',
      'Fig',
      'Papaya',
      'Passionfruit',
      'Lychee',
      'Guava',
      'Dragonfruit',
      'Cranberry',
      'Tangerine',
      'Nectarine',
      'Avocado',
      'Date',
      'Kiwi',
      'Persimmon',
      'Starfruit',
      'Jackfruit',
      'Kumquat',
      'Mandarin',
      'Mulberry',
      'Olive',
      'Pawpaw',
      'Quince',
      'Soursop',
      'Tomato (technically a fruit)',
      'Ackee',
      'Acai berry',
      'Acerola',
      'Amla',
      'Apricot',
      'Barberry',
      'Bilberry',
      'Blackcurrant',
      'Boysenberry',
      'Breadfruit',
      'Cantaloupe',
      'Clementine',
      'Cloudberry',
      'Damson',
      'Durian',
      'Elderberry',
      'Feijoa',
      'Goji berry',
      'Gooseberry',
      'Juniper berry',
      'Lingonberry',
      'Loquat',
      'Mango',
      'Marionberry',
      'Miracle fruit',
      'Mulberry',
      'Nance',
      'Olive',
      'Papaya',
      'Peach',
      'Pear',
      'Persimmon',
      'Pitaya',
      'Pomegranate',
      'Prickly pear',
      'Redcurrant',
      'Salak',
      'Salmonberry',
      'Sapodilla',
      'Soursop',
      'Squash',
      'Tamarillo',
      'Tamarind',
      'Ugli fruit',
      'Yuzu'
    ],
    type: 'name'
  },
  {
    name: 'ClothingBrands',
    data: [
      'Adidas',
      'American Eagle Outfitters',
      'ASOS',
      'Banana Republic',
      'Calvin Klein',
      'Champion',
      'Converse',
      'Diesel',
      'Dolce & Gabbana',
      'Forever 21',
      'GAP',
      'Gucci',
      'H&M',
      'Hollister',
      'Hugo Boss',
      'J.Crew',
      'Lacoste',
      "Levi's",
      'Louis Vuitton',
      'Lululemon',
      "Macy's",
      'Mango',
      'Marks & Spencer',
      'Michael Kors',
      'Nike',
      'Nordstrom',
      'Old Navy',
      'Patagonia',
      'Prada',
      'Primark',
      'Puma',
      'Ralph Lauren',
      'Reebok',
      'Saks Fifth Avenue',
      'Shein',
      'Skechers',
      'Tommy Hilfiger',
      'Uniqlo',
      'Urban Outfitters',
      'Vans',
      "Victoria's Secret",
      'Zara',
      'Abercrombie & Fitch',
      'AllSaints',
      'Ann Taylor',
      'Anthropologie',
      'Banana Republic Factory Store',
      'Bergdorf Goodman',
      "Bloomingdale's",
      'Brooks Brothers',
      'Burlington',
      'Coach',
      "Dillard's",
      'Express',
      'Fast Retailing',
      'Fifth & Pacific',
      'Gap Factory Store',
      'Guess',
      'H&M Divided',
      'Inditex',
      'J.C. Penney',
      "Kohl's",
      'Lane Bryant',
      'Loft',
      'Lord & Taylor',
      "Macy's Backstage",
      'Madewell',
      'Marshalls',
      'maurices',
      'Max Mara',
      'Missguided',
      'Moncler',
      'Neiman Marcus',
      'Nordstrom Rack',
      'Old Navy Outlet',
      "OshKosh B'Gosh",
      'PacSun',
      'Perry Ellis',
      'Polo Ralph Lauren',
      'Rag & Bone',
      'Saks Off 5th',
      'Selfridges',
      'Shopbop',
      'Talbots',
      'Target',
      "The Children's Place",
      'The North Face',
      'Topshop',
      'Tory Burch',
      'Uniqlo U',
      'Urban Outfitters UO',
      'Vince',
      'Warby Parker',
      'Whistles',
      'Williams Sonoma',
      'Yoox Net-a-Porter Group',
      'Zalando',
      'Zegna',
      'Zimmermann',
      '& Other Stories'
    ],
    type: 'name'
  },
  {
    name: 'ClothingMaterials',
    data: [
      'Cotton',
      'Polyester',
      'Silk',
      'Wool',
      'Linen',
      'Denim',
      'Velvet',
      'Leather',
      'Nylon',
      'Spandex',
      'Rayon',
      'Satin',
      'Cashmere',
      'Fleece',
      'Chiffon',
      'Corduroy',
      'Flannel',
      'Tweed',
      'Tulle',
      'Lycra',
      'Acrylic',
      'Tencel',
      'Viscose',
      'Bamboo',
      'Hemp',
      'Angora',
      'Mohair',
      'Alpaca',
      'Taffeta',
      'Georgette',
      'Organza',
      'Jacquard',
      'Crepe',
      'Brocade',
      'Chambray',
      'Faux Fur',
      'Fur',
      'Lace',
      'Canvas',
      'Gabardine',
      'Jersey',
      'Taffeta',
      'Poplin',
      'Batiste',
      'Broderie Anglaise',
      'Linen Blend',
      'Wool Blend',
      'Tweed',
      'Cashmere Blend',
      'Viscose Blend',
      'Acetate',
      'Linen',
      'Modal',
      'Polyamide',
      'Ramie',
      'Tussah Silk',
      'Seersucker',
      'Suede',
      'Bouclé',
      'Piqué',
      'Boucle',
      'Mohair Blend',
      'Angora Blend',
      'Polypropylene',
      'Acetate Blend',
      'Ramie Blend',
      'Faux Leather',
      'Faux Suede',
      'Jute',
      'Seersucker',
      'Chamois',
      'Corduroy',
      'Damask',
      'Eyelet',
      'Moleskin',
      'Muslin',
      'Nanofiber',
      'Oilcloth',
      'Panama Cloth',
      'Plissé',
      'Raschel',
      'Sateen',
      'Shot Silk',
      'Spun Silk',
      'Straw',
      'Tartan',
      'Terry Cloth',
      'Toile',
      'Ultrasuede',
      'Voile',
      'Brocade',
      'Crinoline',
      'Gauze',
      'Bouclé',
      'Grenadine',
      'Taffeta',
      'Tulle',
      'Velvet',
      'Velveteen',
      'Winceyette'
    ],
    type: 'name'
  },
  {
    name: 'Email',
    data: [
      'john.doe@example.com',
      'jane.smith@example.com',
      'michael.jackson@example.com',
      'emma.watson@example.com',
      'peter.parker@example.com',
      'mary.jane@example.com',
      'bruce.wayne@example.com',
      'clark.kent@example.com',
      'tony.stark@example.com',
      'steve.rogers@example.com',
      'diana.prince@example.com',
      'barry.allen@example.com',
      'carol.danvers@example.com',
      'selina.kyle@example.com',
      'harry.potter@example.com',
      'hermione.granger@example.com',
      'ron.weasley@example.com',
      'albus.dumbledore@example.com',
      'gandalf.gray@example.com',
      'frodo.baggins@example.com',
      'aragorn.legolas@example.com',
      'sarah.connor@example.com',
      'john.mcclane@example.com',
      'neo.anderson@example.com',
      'morpheus@example.com',
      'trinity@example.com',
      'marty.mcfly@example.com',
      'doc.brown@example.com',
      'jules.winfield@example.com',
      'vincent.vega@example.com',
      'mia.wallace@example.com',
      'maximus.decimus@example.com',
      'will.turner@example.com',
      'elizabeth.swann@example.com',
      'jack.sparrow@example.com',
      'indiana.jones@example.com',
      'luke.skywalker@example.com',
      'leia.organa@example.com',
      'han.solo@example.com',
      'anakin.skywalker@example.com',
      'padme.amidala@example.com',
      'obiwan.kenobi@example.com',
      'darth.vader@example.com',
      'darth.maul@example.com',
      'yoda@example.com',
      'chewbacca@example.com',
      'bilbo.baggins@example.com',
      'thor.odinson@example.com',
      'loki@example.com',
      'hulk@example.com',
      'ironman@example.com',
      'blackwidow@example.com',
      'captainamerica@example.com',
      'blackpanther@example.com',
      'wolverine@example.com',
      'spiderman@example.com',
      'storm@example.com',
      'cyclops@example.com',
      'jean.grey@example.com',
      'rogue@example.com',
      'gambit@example.com',
      'nightcrawler@example.com',
      'beast@example.com',
      'professorx@example.com',
      'deadpool@example.com',
      'thanos@example.com',
      'rocket@example.com',
      'groot@example.com',
      'starlord@example.com',
      'gamora@example.com',
      'drax@example.com',
      'mantis@example.com',
      'scarletwitch@example.com',
      'vision@example.com',
      'hawkeye@example.com',
      'falcon@example.com',
      'antman@example.com',
      'wasp@example.com',
      'captainmarvel@example.com',
      'groot@example.com',
      'rocket@example.com',
      'drax@example.com',
      'mantis@example.com',
      'scarletwitch@example.com',
      'vision@example.com',
      'hawkeye@example.com',
      'falcon@example.com',
      'antman@example.com',
      'wasp@example.com',
      'captainmarvel@example.com',
      'groot@example.com',
      'rocket@example.com',
      'drax@example.com',
      'mantis@example.com',
      'scarletwitch@example.com',
      'vision@example.com',
      'hawkeye@example.com',
      'falcon@example.com',
      'antman@example.com',
      'wasp@example.com',
      'captainmarvel@example.com'
    ],
    type: 'name'
  },
  {
    name: 'Username',
    data: [
      'adventurous_soul',
      'bookworm_extraordinaire',
      'coffee_lover_99',
      'coding_ninja',
      'creative_mind_21',
      'curious_explorer',
      'dancing_queen_101',
      'digital_artist_42',
      'dream_chaser_88',
      'fashion_forward_77',
      'fitness_fanatic_45',
      'foodie_explorer_32',
      'gamer_girl_64',
      'green_thumb_56',
      'happy_go_lucky_11',
      'home_decor_enthusiast_93',
      'inspirational_speaker_72',
      'introverted_bookworm_23',
      'jet_setting_traveler_48',
      'kind_hearted_soul_19',
      'language_learner_12',
      'laughter_lover_67',
      'makeup_maven_54',
      'mindful_yogi_99',
      'music_lover_47',
      'nature_lover_100',
      'outdoor_adventurer_31',
      'passionate_photographer_85',
      'pet_lover_27',
      'photography_enthusiast_15',
      'plant_lover_62',
      'positive_vibes_91',
      'reader_writer_thinker_94',
      'science_geek_75',
      'skincare_junkie_29',
      'social_butterfly_41',
      'spiritual_seeker_61',
      'style_icon_38',
      'tech_savvy_73',
      'the_real_foodie_52',
      'travel_holic_83',
      'wanderlust_explorer_25',
      'wine_enthusiast_92',
      'yoga_lover_78',
      'zen_master_13',
      'always_learning_22',
      'beach_bum_76',
      'bookaholic_18',
      'cat_lady_33',
      'coffee_addict_63',
      'creative_soul_44',
      'curious_mind_53',
      'dreamer_believer_97',
      'fashionista_96',
      'fitness_junkie_90',
      'foodie_at_heart_82',
      'gamer_boy_26',
      'green_thumb_mama_57',
      'happy_go_lucky_36',
      'home_decor_lover_14',
      'inspiring_leader_74',
      'introverted_writer_20',
      'jet_setter_30',
      'kind_hearted_16',
      'language_lover_89',
      'laughter_is_the_best_medicine_37',
      'makeup_artist_43',
      'mindful_yogi_59',
      'music_lover_40',
      'nature_lover_98',
      'outdoor_enthusiast_55',
      'passionate_artist_81',
      'pet_parent_28',
      'photography_lover_17',
      'plant_mom_58',
      'positive_vibes_only_95',
      'reader_writer_thinker_71',
      'science_enthusiast_79',
      'skincare_addict_49',
      'social_butterfly_80',
      'spiritual_seeker_60',
      'style_maven_35',
      'tech_savvy_69',
      'the_real_foodie_51',
      'travel_holic_84',
      'wanderlust_explorer_24',
      'wine_lover_93',
      'yoga_lover_77',
      'zen_master_10',
      'always_learning_21',
      'beach_lover_70',
      'bookworm_extraordinaire_18',
      'coffee_lover_65',
      'creative_mind_43',
      'curious_explorer_50',
      'dancing_queen_10',
      'digital_artist_41',
      'dream_chaser_87',
      'fashion_forward_78',
      'fitness_fanatic_46'
    ],
    type: 'name'
  }
]
